In [31]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [35]:
heart_df =  pd.read_csv("heart.csv")

In [37]:
heart_df.sample(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
458   43    1   0       150   247    0        1      171      0      1.5   
272   39    0   2       138   220    0        1      152      0      0.0   
463   43    1   0       110   211    0        1      161      0      0.0   
452   66    0   0       178   228    1        1      165      1      1.0   
418   62    0   0       124   209    0        1      163      0      0.0   
44    55    0   1       132   342    0        1      166      0      1.2   
564   56    1   0       132   184    0        0      105      1      2.1   
956   49    0   0       130   269    0        1      163      0      0.0   
994   59    1   0       110   239    0        0      142      1      1.2   
208   38    1   2       138   175    0        1      173      0      0.0   

     slope  ca  thal  target  
458      2   0     2       1  
272      1   0     2       1  
463      2   0     3       1  
452      1   2     3       0  
418      2   0     2       1  
44       2   0     2       1  
564      1   1     1       0  
956      2   0     2       1  
994      1   1     3       0  
208      2   4     2       1

In [39]:
heart_df.shape

(1025, 14)

In [41]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [45]:
columns_to_convert = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang','slope','ca','thal','target'] 

heart_df[columns_to_convert] = heart_df[columns_to_convert].astype('int16')

In [56]:
heart_df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [60]:
heart_df.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [181]:
heart_df.sample(4)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
630   45    1   3       110   264    0        1      132      0      1.2   
608   64    1   0       145   212    0        0      132      0      2.0   
401   71    0   0       112   149    0        1      125      0      1.6   
314   40    1   3       140   199    0        1      178      1      1.4   

     slope  ca  thal  target  
630      1   0     3       0  
608      1   2     1       0  
401      1   0     2       1  
314      2   0     3       1

In [145]:
heart_df['cp'].value_counts()

cp
0    497
2    284
1    167
3     77
Name: count, dtype: int64

In [179]:
heart_df['fbs'].value_counts()

fbs
0    872
1    153
Name: count, dtype: int64

1-> True (High Fasting Blood Sugar) 

0-> False (normal Fasting blood sugar) 

In [152]:
heart_df['restecg'].value_counts()

restecg
1    513
0    497
2     15
Name: count, dtype: int64

0: Normal

1: ST-T wave abnormality (e.g., T wave inversions or ST elevation/depression)

2: Showing probable or definite left ventricular hypertrophy (by Estes' criteria)

In [155]:
heart_df['exang'].value_counts()

exang
0    680
1    345
Name: count, dtype: int64

Indicates whether the patient experiences angina during exercise:

1: Yes

0: No

In [159]:
heart_df['slope'].value_counts()

slope
1    482
2    469
0     74
Name: count, dtype: int64

slope (Slope of the Peak Exercise ST Segment)

Describes the slope of the ST segment during peak exercise:

o: Upsloping

1: Flat

2: Downsloping


In [171]:
heart_df['ca'].value_counts()

ca
0    578
1    226
2    134
3     69
4     18
Name: count, dtype: int64

In [165]:
heart_df['thal'].value_counts()

thal
2    544
3    410
1     64
0      7
Name: count, dtype: int64

 thal (Thalassemia)

Describes a blood disorder or the type of defect in the heart:

0 = normal; 1 = fixed defect; 2 = reversable defect

3: Normal

6: Fixed defect

7: Reversible defect

In [64]:
heart_df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

1 --> Defective heart

0 --> Health Heart 

In [90]:
features = heart_df.drop(columns=['target'],axis=1)
target = heart_df['target']

In [98]:
X_train,X_test,y_train,y_test = train_test_split(features,target,test_size=0.2,stratify=target, random_state=2)

In [106]:
model = LogisticRegression() 


In [108]:
model.fit(X_train,y_train)

C:\Users\samar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [118]:
X_train_pred = model.predict(X_train) 
trainingDataAcc = accuracy_score(X_train_pred,y_train)

In [120]:
trainingDataAcc

0.8524390243902439

In [122]:
X_test_pred = model.predict(X_test) 
TestDataAcc = accuracy_score(X_test_pred,y_test)

In [124]:
TestDataAcc

0.8048780487804879

## Building the Predictive system

In [139]:
input_data = (41,0,1,130,204,0,0,172,0,1.4,2,0,2)

inputs = np.array(input_data).reshape(1,-1)
print(model.predict(inputs)[0])

1


C:\Users\samar\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [143]:
import pickle

# Save the model
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

# Load the model
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

print(loaded_model.predict(inputs)[0])  # Predict using the loaded model


1


C:\Users\samar\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [177]:
# Importing necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, recall_score, precision_score

# Assuming features and target are already defined
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, stratify=target, random_state=2)

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Machine": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

# Creating an empty dictionary to store the results
results = {}

# Looping through each model
for model_name, model in models.items():
    # Fitting the model
    model.fit(X_train, y_train)
    
    # Making predictions
    y_pred = model.predict(X_test)
    
    # Evaluating the model
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    
    # Storing the results
    results[model_name] = {
        "Accuracy": accuracy,
        "Confusion Matrix": cm,
        "F1 Score": f1,
        "Recall": recall,
        "Precision": precision
    }

# Printing the results for each model
for model_name, metrics in results.items():
    print(f"Model: {model_name}")
    print(f"Accuracy: {metrics['Accuracy']:.4f}")
    print(f"Confusion Matrix:\n{metrics['Confusion Matrix']}")
    print(f"F1 Score: {metrics['F1 Score']:.4f}")
    print(f"Recall: {metrics['Recall']:.4f}")
    print(f"Precision: {metrics['Precision']:.4f}")
    print("-" * 50)


C:\Users\samar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Model: Logistic Regression
Accuracy: 0.8049
Confusion Matrix:
[[72 28]
 [12 93]]
F1 Score: 0.8230
Recall: 0.8857
Precision: 0.7686
--------------------------------------------------
Model: Support Vector Machine
Accuracy: 0.7073
Confusion Matrix:
[[63 37]
 [23 82]]
F1 Score: 0.7321
Recall: 0.7810
Precision: 0.6891
--------------------------------------------------
Model: Decision Tree
Accuracy: 1.0000
Confusion Matrix:
[[100   0]
 [  0 105]]
F1 Score: 1.0000
Recall: 1.0000
Precision: 1.0000
--------------------------------------------------
Model: Random Forest
Accuracy: 1.0000
Confusion Matrix:
[[100   0]
 [  0 105]]
F1 Score: 1.0000
Recall: 1.0000
Precision: 1.0000
--------------------------------------------------
Model: K-Nearest Neighbors
Accuracy: 0.7220
Confusion Matrix:
[[74 26]
 [31 74]]
F1 Score: 0.7220
Recall: 0.7048
Precision: 0.7400
--------------------------------------------------
Model: Naive Bayes
Accuracy: 0.7805
Confusion Matrix:
[[75 25]
 [20 85]]
F1 Score: 0.7907
R